### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by ianb** [mozilla/activities#2]
When I install the xpi (after applied pull 1), I get this exception:

```
Traceback (most recent call last):
  File "resource:///modules/XPIProvider.jsm", line 5010, in null
    callbacks.forEach(function(aCallback) {
  File "resource:///modules/XPIProvider.jsm", line 5011, in null
    aCallback(aAddon);
  File "resource:///modules/XPIProvider.jsm", line 4099, in null
    AddonRepository.getCachedAddonByID(aAddon.id, completeAddon);
  File "resource:///modules/AddonRepository.jsm", line 512, in null
    aCallback(null);
  File "resource:///modules/XPIProvider.jsm", line 4095, in completeAddon
    self.callback(self.addons);
  File "resource:///modules/XPIProvider.jsm", line 5133, in null
    aCallback(aAddons[0]);
  File "resource:///modules/XPIProvider.jsm", line 6754, in null
    reason);
  File "resource:///modules/XPIProvider.jsm", line 3711, in XPI_callBootstrapMethod
    this.bootstrapScopes[aId][aMethod](params, aReason);
  File "jar:file:///Users/ianbicking/src/seeitsaveit/Profile/extensions/webactivities@mozillalabs.com.xpi!/bootstrap.js", line 180, in startup
    prefsURI: rootURI + 'defaults/preferences/prefs.js'
  File "resource://webactivities-at-mozillalabs-dot-com/api-utils/lib/addon/runner.js", line 99, in startup
    quit: exit
  File "resource://webactivities-at-mozillalabs-dot-com/activities/lib/main.js", line 99, in null
    MozActivitiesAPIClassID, "MozActivitiesAPI", MozActivitiesAPIContract, MozActivitiesAPIFactory
[Exception... "Component returned failure code: 0xc1f30100 (NS_ERROR_FACTORY_EXISTS) [nsIComponentRegistrar.registerFactory]"  nsresult: "0xc1f30100 (NS_ERROR_FACTORY_EXISTS)"  location: "JS frame :: resource://webactivities-at-mozillalabs-dot-com/api-utils/lib/loader.js -> resource://webactivities-at-mozillalabs-dot-com/activities/lib/main.js :: <TOP_LEVEL> :: line 99"  data: no]
Bootstrap error: Component returned failure code: 0xc1f30100 (NS_ERROR_FACTORY_EXISTS) [nsIComponentRegistrar.registerFactory]
undefined: 99
```

After restart there's no exception, but there's also no exposed navigator.registerActivityHandler, so I'm assuming the addon failed to install.

**Comment by ianb** [comment]
defunct branch
